#pragma once
// Outlast (1.0) SDK

#include <set>
#include <string>

#include "SDK/OL_Basic.hpp"

#include "SDK/OL_Core_structs.hpp"
#include "SDK/OL_Core_classes.hpp"
#include "SDK/OL_Core_parameters.hpp"
#include "SDK/OL_Engine_structs.hpp"
#include "SDK/OL_Engine_classes.hpp"
#include "SDK/OL_Engine_parameters.hpp"
#include "SDK/OL_GameFramework_structs.hpp"
#include "SDK/OL_GameFramework_classes.hpp"
#include "SDK/OL_GameFramework_parameters.hpp"
#include "SDK/OL_UDKBase_structs.hpp"
#include "SDK/OL_UDKBase_classes.hpp"
#include "SDK/OL_UDKBase_parameters.hpp"
#include "SDK/OL_IpDrv_structs.hpp"
#include "SDK/OL_IpDrv_classes.hpp"
#include "SDK/OL_IpDrv_parameters.hpp"
#include "SDK/OL_OnlineSubsystemSteamworks_structs.hpp"
#include "SDK/OL_OnlineSubsystemSteamworks_classes.hpp"
#include "SDK/OL_OnlineSubsystemSteamworks_parameters.hpp"
#include "SDK/OL_WinDrv_structs.hpp"
#include "SDK/OL_WinDrv_classes.hpp"
#include "SDK/OL_WinDrv_parameters.hpp"
#include "SDK/OL_AkAudio_structs.hpp"
#include "SDK/OL_AkAudio_classes.hpp"
#include "SDK/OL_AkAudio_parameters.hpp"
#include "SDK/OL_GFxUI_structs.hpp"
#include "SDK/OL_GFxUI_classes.hpp"
#include "SDK/OL_GFxUI_parameters.hpp"
#include "SDK/OL_XAudio2_structs.hpp"
#include "SDK/OL_XAudio2_classes.hpp"
#include "SDK/OL_XAudio2_parameters.hpp"
#include "SDK/OL_OnlineSubsystemPC_structs.hpp"
#include "SDK/OL_OnlineSubsystemPC_classes.hpp"
#include "SDK/OL_OnlineSubsystemPC_parameters.hpp"
#include "SDK/OL_OLGame_structs.hpp"
#include "SDK/OL_OLGame_classes.hpp"
#include "SDK/OL_OLGame_parameters.hpp"
